// packages/simplebar-react/index.js
import React from 'react';
import PropTypes from 'prop-types';
import '@bitsler/simplebar';

export default function SimpleBar({
  children,
  scrollableNodeProps,
  ...options
}) {
  return (
    <div data-simplebar {...options}>
      <div className="simplebar-wrapper">
        <div className="simplebar-height-auto-observer-wrapper">
          <div className="simplebar-height-auto-observer" />
        </div>
        <div className="simplebar-mask">
          <div className="simplebar-offset">
            <div className="simplebar-content-wrapper">
              <div
                {...scrollableNodeProps}
                className={`simplebar-content${
                  scrollableNodeProps && scrollableNodeProps.className
                    ? ` ${scrollableNodeProps.className}`
                    : ''
                }`}
              >
                {children}
              </div>
            </div>
          </div>
        </div>
        <div className="simplebar-placeholder" />
      </div>
      <div className="simplebar-track simplebar-horizontal">
        <div className="simplebar-scrollbar" />
      </div>
      <div className="simplebar-track simplebar-vertical">
        <div className="simplebar-scrollbar" />
      </div>
    </div>
  );
}

SimpleBar.propTypes = {
  children: PropTypes.node
};

// packages/simplebar-vue/index.vue
<template>
  <div
    data-simplebar
  >
    <div class="simplebar-wrapper">
        <div class="simplebar-height-auto-observer-wrapper">
          <div class="simplebar-height-auto-observer" />
        </div>
        <div class="simplebar-mask">
          <div class="simplebar-offset">
            <div class="simplebar-content-wrapper">
              <div class="simplebar-content">
                <slot></slot>
              </div>
            </div>
          </div>
        </div>
        <div class="simplebar-placeholder" />
      </div>
      <div class="simplebar-track simplebar-horizontal">
        <div class="simplebar-scrollbar" />
      </div>
      <div class="simplebar-track simplebar-vertical">
        <div class="simplebar-scrollbar" />
      </div>
  </div>
</template>

<script>
import '@bitsler/simplebar';
export default {
  name: 'simplebar-vue'
}
</script>
